name: Build and Deploy

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Preset Image Name
        run: |
          IMAGE_URL="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${GITHUB_SHA::7}"
          IMAGE_URL=$(echo $IMAGE_URL | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          provenance: false

      - id: deploy
        name: Deploy Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPTAINROVER_SERVER }}
          app: ${{ secrets.CAPTAINROVER_APP_NAME }}
          token: ${{ secrets.CAPTAINROVER_APP_TOKEN }}
          image: ${{ env.IMAGE_URL }}

      - name: Show Deployment Output
        run: 'echo "Deployment URL: ${{ steps.deploy.outputs.url }}"'
