name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Preset Image Name
        run: |
          IMAGE_URL="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${GITHUB_SHA::7}"
          IMAGE_URL=$(echo $IMAGE_URL | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV

      # 👇 This ensures the image is pushed as PUBLIC
      - name: Configure image visibility to public
        run: |
          echo "{\"visibility\":\"public\"}" > metadata.json

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
          outputs: type=registry
          annotations: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}

      - id: deploy
        name: Deploy Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPTAINROVER_SERVER }}
          app: ${{ secrets.CAPTAINROVER_APP_NAME }}
          token: ${{ secrets.CAPTAINROVER_APP_TOKEN }}
          image: ${{ env.IMAGE_URL }}

      - name: Show Deployment Output
        run: 'echo "Deployment URL: ${{ steps.deploy.outputs.url }}"'
